version: 2.1
parameters:
  kre-image-tag:
    type: string
    default: "latest"
jobs:
  build:
    docker:
      - image: katalonstudio/katalon:<< pipeline.parameters.kre-image-tag >>
    steps:
      - run:
          name: Execute test
          command: |
            set -x
            set -o nounset

            printenv

            mkdir /agent

            cd /agent

            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            echo "${JOB_INFO}" >> job.json
            echo "${AGENT_CONFIG}" >> agentconfig

            chmod 777 *
            ls -al

            ./agent start-agent --ci