version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      #- checkout
      - run: wget -O ci-samples.zip https://phucknguyen.s3.us-west-2.amazonaws.com/ci-samples.zip # download zip file from s3
      - run: unzip ci-samples.zip # unzip the downloaded file
      - run: cd ci-samples/ # go into the unzip folder
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
