version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - run:
          name: Execute test
          command: |
            set -x
            set -o nounset

            printenv

            mkdir /agent

            cd /agent

            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            cat "${AGENT_CONFIG}" >> agentconfig
            cat "${JOB_INFO}" >> job.json

            chmod 777 *
            ls -al

            ./agent start-agent --ci