version: 2.1

# parameters:
#   kre-image-tag:
#     type: string
#     default: "latest"
#   agent-download-link:
#     type: string
#     default: ""
#   job-info:
#     type: string
#     default: ""
#   agent-config:
#     type: string
#     default: ""

jobs:
  build:
    parameters:
      kre-image-tag:
        type: string
        default: "latest"
      agent-download-link:
        type: string
        default: ""
      job-info:
        type: string
        default: ""
      agent-config:
        type: string
        default: ""
    docker:
      - image: katalonstudio/katalon:<< parameters.kre-image-tag >>
    environment:
      AGENT_DOWNLOAD_LINK: << parameters.agent-download-link >>
      JOB_INFO: << parameters.job-info >>
      AGENT_CONFIG:  << parameters.agent-config >>
    steps:
      - run:
          name: Execute test
          command: |
            set -x
            set -o nounset

            printenv

            mkdir /agent

            cd /agent

            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            echo "${JOB_INFO}" >> job.json
            echo "${AGENT_CONFIG}" >> agentconfig

            chmod 777 *
            ls -al

            ./agent start-agent --ci