version: 2.1

# parameters:
#   kre-image-tag:
#     type: string
#     default: "latest"
#   agent-download-link:
#     type: string
#     default: ""
#   job-info:
#     type: string
#     default: ""
#   agent-config:
#     type: string
#     default: ""

parameters:
  ks_version:
    type: string
    default: "latest"
  agent_download_link:
    type: string
    default: ""
  job_info:
    type: string
    default: ""
  agent_config:
    type: string
    default: ""

jobs:
  build:
    docker:
      - image: katalonstudio/katalon:<< parameters.ks_version >>
    environment:
      AGENT_DOWNLOAD_LINK: << parameters.agent_download_link >>
      JOB_INFO: << parameters.job_info >>
      AGENT_CONFIG:  << parameters.agent_config >>
    steps:
      - run:
          name: Execute test
          command: |
            set -x
            set -o nounset

            printenv

            mkdir /agent

            cd /agent

            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            echo "${JOB_INFO}" >> job.json
            echo "${AGENT_CONFIG}" >> agentconfig

            chmod 777 *
            ls -al

            ./agent start-agent --ci